/* Main.ino file generated by New Project wizard
 *
 * Created:   Tue May 14 2024
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---
const int ledPin = 0;

const int m1_en = 3;
const int m2_en = 5;
const int m3_en = 6;

const int m1_in1 = 0;
const int m1_in2 = 1;
const int m2_in1 = 2;
const int m2_in2 = 4;
const int m3_in1 = 7;
const int m3_in2 = 8;

const float input_low_range = 0;
const float input_high_range = 0;

void move(double x, double y, double w)
{
   if (isnan(x) || isnan(y)) 
   {
      Serial.print("Invalid input: x or y is not a number.");
      return;
   }

    // Define angles in radians (assuming conversion from degrees was done elsewhere)
    const double angle1 = 30.0; //* M_PI / 180.0;
    const double angle2 = 150.0; //* M_PI / 180.0;
    const double angle3 = 270.0; //* M_PI / 180.0;

    // Create the transformation matrix
    double A[3][3] = {
      {cos(angle1), cos(angle2), cos(angle3)},
      {sin(angle1), sin(angle2), sin(angle3)},
      {1.0, 1.0, 1.0}
    };

    // Create the order vector
    double order[3] = {x, y, w};

    // Perform matrix multiplication
    double result[3];
    for (int i = 0; i < 3; i++) {
      result[i] = 0.0;
      for (int j = 0; j < 3; j++) {
	result[i] += A[i][j] * order[j];
       }
     }

   // Handle the result (motor controls or further processing)
   // ... (replace with your logic for motor controls or other use of the result)
   Serial.print("Result (x', y', w'): ");
   Serial.print(result[0]);
   Serial.print(", ");
   Serial.print(result[1]);
   Serial.print(", ");
   Serial.println(result[2]);     
   
   
   double val_m1 = result[0];
   double val_m2 = result[1];
   double val_m3 = result[2];
   if (val_m1 >= 0)
   {
      digitalWrite(m1_in1, HIGH);
      digitalWrite(m1_in2, LOW);
   } else 
   {
      digitalWrite(m1_in1, LOW);
      digitalWrite(m1_in2, HIGH);
   }
   analogWrite(m1_en, map(val_m1, input_low_range, input_high_range, 0, 255));
   
   if (val_m1 >= 0)
   {
      digitalWrite(m2_in1, HIGH);
      digitalWrite(m2_in2, LOW);
   } else 
   {
      digitalWrite(m2_in1, LOW);
      digitalWrite(m2_in2, HIGH);
   }
   analogWrite(m2_en, map(val_m2, input_low_range, input_high_range, 0, 255));
   
   if (val_m1 >= 0)
   {
      digitalWrite(m3_in1, HIGH);
      digitalWrite(m3_in2, LOW);
   } else 
   {
      digitalWrite(m3_in1, LOW);
      digitalWrite(m3_in2, HIGH);
   }
   analogWrite(m3_en, map(val_m3, input_low_range, input_high_range, 0, 255));
 }

void setup () {
peripheral_setup();
// TODO: put your setup code here, to run once:
pinMode(ledPin, OUTPUT);
pinMode(m1_en, OUTPUT);
pinMode(m2_en, OUTPUT);
pinMode(m3_en, OUTPUT);

pinMode(m1_in1, OUTPUT);
pinMode(m1_in2, OUTPUT);
pinMode(m2_in1, OUTPUT);
pinMode(m2_in2, OUTPUT);
pinMode(m3_in1, OUTPUT);
pinMode(m3_in2, OUTPUT);
move(1, 1, 0);
}

void loop() {
peripheral_loop(); // TODO: put your main code here, to run repeatedly:
}
